### ISSUE TITLE
Debian support

### ISSUE THREAD

**Issue by mrbluecoat** [ericwoud/buildR64arch#10]
Any chance you would bring back Debian as an OS option?

**Comment by ericwoud** [comment]
This project relies heavily on the packages build. There are a lot of similarities between debian and Archlinux, but the package structure is not one of them. So, sadly, no.

But frank-w has debian images for all Banana pi routers. You can use that.

Another option is to create an ArchLinuxArm image and then replace all the files. You could use the files from the image of frank-w,  or setup your own rootfs and use the configuration files from ArchLinuxArm image.

Any reason why you prefer this project, over using existing debian images?

**Comment by mrbluecoat** [comment]
Got it, thanks
