### ISSUE TITLE
Bad device selected

### ISSUE THREAD

**Issue by iz4tow** [ericwoud/buildR64arch#11]
Good morning,
I'm trying to use your script to insall arch on BPI-R3 but when I launch it with -F option it select my nvme local disk instead of mmcblk0

```
/build.sh -F
Current dir: /home/user/BANANAPI/buildR64arch
Compatible:
Host Arch: x86_64
rootdev=/dev/nvme0n1p3 , do not use.
pkroot=nvme0n1 , do not use.
1) bpir64 Bananapi-R64
2) bpir3  Bananapi-R3
3) bpir3m Bananapi-R3-Mini
4) bpir4  Bananapi-R4
5) Quit
Choose target to format image for: 
```

**Comment by ericwoud** [comment]
See the comment it puts after it:
```
rootdev=/dev/nvme0n1p3 , do not use.
pkroot=nvme0n1 , do not use.
```
So the script removes nvme0n1 as possible option later, when you get to choose which drive to format.
