### ISSUE TITLE
[ Feature Request ] Enable System Updates and Package Installation

### ISSUE THREAD

**Issue by GiovanniBalestrieri** [ericwoud/buildR64arch#13]
I wanted to start by thanking you for your recent commit, which allowed me to successfully build the minimal ArchLinux image. The process worked well, and I'm excited to continue exploring its capabilities.

As part of my next steps, I intended to update the system and install additional packages. My initial approach was to connect an Ethernet cable from my main home router to the Banana Pi R3, expecting to obtain an internet connection. However, I found myself needing some guidance on how to properly set up the network to get an IP address assigned.

Since I couldn't find relevant instructions in the README, I attempted the following setup:

Create a 05-wan.link file

```
[userk@bpir3 ~]$ sudo nano /etc/systemd/network/05-wan.link
[Match]
OriginalName=wan

[Link]
Name=wan
```

Create a 07-wan.network 
```
[userk@bpir3 ~]$ sudo nano /etc/systemd/network/07-wan.network
[Match]
Name=wan

[Network]
BindCarrier=eth0
DHCP=yes
IPForward=yes

```
Then restart networkd with:
`sudo systemctl restart systemd-networkd`

While this approach has helped me move forward, I believe that enabling system updates and package installations through a straightforward network setup is a critical feature. I kindly suggest considering this as a feature request or perhaps adding more detailed guidance in the README to assist users with network configuration.

**Comment by ericwoud** [comment]
The setup RTnoSFP does exactly that to setup wan as internet connection and more.... (nftables and such). The normal RT sets up the sfp-wan port for internet.
