### ISSUE TITLE
Build fails because ftp server is unavailable

### ISSUE THREAD

**Issue by attilabody** [ericwoud/buildR64arch#5]
`curl: (7) Failed to connect to ftp.woudstra.mywire.org port 21 after 20 ms: Couldn't connect to server`
Hint: If there are any artifacts needed to build the image, consider moving them either to Github or public Google Drive

**Comment by ericwoud** [comment]
It is fixed, see buildRKarch repo issue.

Normally there is a backup repo on GitHub. Using it will be fixed also soon. (Only one 'y' to add)

GDrive does not allow automated uploads, nor do many of the alternatives. Also the backup repo is uploaded manually. 

The ftp server hosts automated builds, updated daily/weekly/monthly. It allows for a daily check for new linux stable kernel and such and building it and having it available for download automatically.

In case an automated build is non functional, there is always a working version of the package available in the backup repo on GitHub.

**Comment by ericwoud** [comment]
The backup repo is also updated and reworked. Some packages have a colon in the filename (epoch number) and github does not support it and converts it to a dot. The .db is corrected accordingly.
