### ISSUE TITLE
Set CONFIG_TUN=m in kernel config to make tun.ko

### ISSUE THREAD

**Issue by ostrich** [ericwoud/buildR64arch#8]
Please consider setting `CONFIG_TUN=m` in your kernel config so we get the tun.ko module. Thanks!

```
$ zcat /proc/config.gz | grep CONFIG_TUN
# CONFIG_TUN is not set
# CONFIG_TUN_VNET_CROSS_LE is not set
```

**Comment by gurudvlp** [comment]
@ostrich I agree that it would be great to have this compiled in.  I have started playing with building another kernel that has this feature, FUSE, and various file system support added.  The build is automated but it is not to the point of having its own repo set up yet.

You can see the build scripts at [https://github.com/Gurumode/kernel-get](url).  I built a kernel this morning with:

`CONFIG_TUN=y
CONFIG_TUN_VNET_CROSS_LE=y`

I have not tested this build, but you are free to download and try it at [https://gurumode.net/kernel/linux-6.3.9-bpi-gurumode/](url).  I think it can be used by replacing the Image file in /boot, and running `sudo bpir-writefip`.  It will be overwritten the next time you update though.

**Comment by ostrich** [comment]
Thanks @gurudvlp, I gave it a shot. It boots and Tailscale works with tunl0. Unfortunately wlan0 and wlan1 are no longer being created.

**Comment by gurudvlp** [comment]
Well that is not good.  Can you provide the steps that you took to install the new kernel?  Like I said, I had not yet tested it but would have though the most likely thing would be a failure to boot.  I'll install and see if I can find what is going wrong.

**Comment by ericwoud** [comment]
It is set and build. Update the linux-bpir64-git package and reboot.

You're all set.


But it is quite easy to edit a package from the aur.

First install if not already:

`pacman -Syu base-devel git`

Check the following package:

https://aur.archlinux.org/packages/linux-bpir64-git

So as non-root user:

`git clone https://aur.archlinux.org/linux-bpir64-git.git`

`cd linux-bpir64-git`

`nano defconfig`

Edit the defconfig file, save and exit

`makepkg -fsi`
